"""create transactional schema

Revision ID: 54732d95c12b
Revises:
Create Date: 2026-07-15 11:49:29.555290
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "54732d95c12b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_ts"), "audit_log", ["ts"], unique=False)
    op.create_table(
        "members",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("github_login", sa.String(length=255), nullable=False),
        sa.Column("github_user_id", sa.BigInteger(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("added_by", sa.String(length=255), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_user_id"),
    )
    op.create_index(op.f("ix_members_github_login"), "members", ["github_login"], unique=True)
    op.create_table(
        "org_config",
        sa.Column("org_login", sa.String(length=255), nullable=False),
        sa.Column("default_field_name", sa.String(length=255), nullable=True),
        sa.Column("project_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("excluded_projects", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("org_login"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_outbox_pending", "outbox_events", ["exported_at", "id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("org", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "repositories",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("github_repository_id", sa.BigInteger(), nullable=True),
        sa.Column("full_name", sa.String(length=512), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_repository_id"),
    )
    op.create_index(op.f("ix_repositories_full_name"), "repositories", ["full_name"], unique=True)
    op.create_table(
        "issues",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column("github_issue_id", sa.String(length=255), nullable=True),
        sa.Column("issue_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_issue_id"),
        sa.UniqueConstraint("repository_id", "issue_number"),
    )
    op.create_index(op.f("ix_issues_repository_id"), "issues", ["repository_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by_member_id", sa.BigInteger(), nullable=False),
        sa.Column("updated_by_member_id", sa.BigInteger(), nullable=True),
        sa.Column("deleted_by_member_id", sa.BigInteger(), nullable=True),
        sa.Column("github_user", sa.String(length=255), nullable=False),
        sa.Column("github_user_id", sa.BigInteger(), nullable=True),
        sa.Column("created_by_user", sa.String(length=255), nullable=False),
        sa.Column("context_type", sa.String(length=20), nullable=False),
        sa.Column("repository_id", sa.BigInteger(), nullable=True),
        sa.Column("issue_id", sa.BigInteger(), nullable=True),
        sa.Column("repo", sa.String(length=512), nullable=True),
        sa.Column("issue_number", sa.Integer(), nullable=False),
        sa.Column("issue_title", sa.Text(), nullable=True),
        sa.Column("issue_url", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("category_title", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), nullable=False),
        sa.Column("duration_hours", sa.Float(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("synced_to_project", sa.Boolean(), nullable=False),
        sa.Column("takt_version", sa.String(length=100), nullable=True),
        sa.Column("client_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inserted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(op.f("ix_sessions_completed_at"), "sessions", ["completed_at"], unique=False)
    op.create_index(op.f("ix_sessions_deleted_at"), "sessions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_sessions_github_user"), "sessions", ["github_user"], unique=False)
    op.create_index(op.f("ix_sessions_member_id"), "sessions", ["member_id"], unique=False)
    op.create_index("ix_sessions_repo_issue", "sessions", ["repo", "issue_number"], unique=False)
    op.create_index(
        "ix_sessions_user_completed", "sessions", ["github_user", "completed_at"], unique=False
    )
    op.create_table(
        "session_projects",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("project_title_snapshot", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("session_id", "project_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_projects")
    op.drop_index("ix_sessions_user_completed", table_name="sessions")
    op.drop_index("ix_sessions_repo_issue", table_name="sessions")
    op.drop_index(op.f("ix_sessions_member_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_github_user"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_deleted_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_completed_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_issues_repository_id"), table_name="issues")
    op.drop_table("issues")
    op.drop_index(op.f("ix_repositories_full_name"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_table("projects")
    op.drop_index("ix_outbox_pending", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("org_config")
    op.drop_index(op.f("ix_members_github_login"), table_name="members")
    op.drop_table("members")
    op.drop_index(op.f("ix_audit_log_ts"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
