"""map clients through projects

Revision ID: eee273252511
Revises: 79612f0cd15e
Create Date: 2026-07-17 10:31:57.644261
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "eee273252511"
down_revision: str | None = "79612f0cd15e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_projects",
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_index(
        op.f("ix_client_projects_client_id"), "client_projects", ["client_id"], unique=False
    )
    op.create_table(
        "project_repositories",
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "repository_id"),
    )
    op.execute(
        """
        INSERT INTO client_projects (project_id, client_id, created_at)
        SELECT DISTINCT sp.project_id, cr.client_id, CURRENT_TIMESTAMP
        FROM client_repositories cr
        JOIN sessions s ON s.repository_id = cr.repository_id
        JOIN session_projects sp ON sp.session_id = s.session_id
        ON CONFLICT (project_id) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO project_repositories (project_id, repository_id, created_at)
        SELECT DISTINCT sp.project_id, s.repository_id, CURRENT_TIMESTAMP
        FROM sessions s
        JOIN session_projects sp ON sp.session_id = s.session_id
        WHERE s.repository_id IS NOT NULL
        ON CONFLICT (project_id, repository_id) DO NOTHING
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_repositories")
    op.drop_index(op.f("ix_client_projects_client_id"), table_name="client_projects")
    op.drop_table("client_projects")
    # ### end Alembic commands ###
