"""Pydantic models for the API wire format."""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, computed_field, model_validator

# --- Identity ---


class GitHubUser(BaseModel):
    """Resolved identity from a PAT — what GitHub returned for /user."""

    login: str
    id: int


class Me(BaseModel):
    """Response from /v1/me — extension uses this to gate UI."""

    login: str
    id: int
    role: Literal["admin", "member"]
    status: Literal["active", "revoked", "pending"]
    org_member: bool


# --- Sessions ---


class SessionIn(BaseModel):
    """A normalized time entry from either GitHub or the manual tool."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    session_id: str = Field(description="UUID generated by the extension at START time.")
    source: Literal["github", "manual"] | None = None
    entry_type: Literal["delivery", "ops"] | None = Field(default=None, alias="type")
    client_id: int | None = None
    client: str | None = None
    repo: str | None = Field(default=None, description="owner/name")
    reporting_project_id: str | None = None
    project: str | None = None
    issue_number: int = Field(default=0, ge=0)
    issue_title: str | None = None
    issue_url: str | None = None
    description: str | None = None
    github_metadata: dict = Field(default_factory=dict)
    member_login: str | None = Field(
        default=None, description="Admin-only attributed member for historical entries."
    )
    started_at: datetime
    completed_at: datetime
    duration_ms: int = Field(ge=0)
    duration_hours: float = Field(ge=0)
    duration_hours_exact: float | None = Field(default=None, ge=0)
    source_url: str | None = None
    synced_to_project: bool = False
    project_titles: list[str] = Field(default_factory=list)
    project_ids: list[str] = Field(default_factory=list)
    takt_version: str | None = None
    client_ts: datetime | None = None
    context_type: Literal["issue", "repository", "category"] | None = Field(
        default=None, exclude=True
    )
    category: str | None = Field(default=None, exclude=True)
    category_title: str | None = Field(default=None, exclude=True)
    title: str | None = Field(default=None, exclude=True)

    @model_validator(mode="after")
    def normalize_entry(self) -> "SessionIn":
        self.source = self.source or (
            "github" if self.source_url and self.issue_number > 0 else "manual"
        )
        if self.source == "github":
            self.entry_type = "delivery"
        elif self.entry_type is None:
            self.entry_type = "delivery" if self.project_ids else "ops"
        self.description = self.description or self.category_title or self.issue_title or self.title
        if self.reporting_project_id is None and self.project_ids:
            self.reporting_project_id = self.project_ids[0]
        if self.project is None and self.project_titles:
            self.project = self.project_titles[0]
        if self.source == "github" and not self.github_metadata:
            self.github_metadata = {
                "schema_version": 1,
                "repository": self.repo,
                "issue_number": self.issue_number,
                "issue_title": self.issue_title,
                "issue_url": self.issue_url,
                "source_url": self.source_url,
            }
        if self.entry_type == "ops":
            self.repo = None
            self.reporting_project_id = None
            self.project = None
            self.issue_number = 0
            self.issue_title = None
            self.issue_url = None
            self.project_ids = []
            self.project_titles = []
            self.synced_to_project = False
        return self


class SessionOut(SessionIn):
    """A session returned from the transactional store."""

    ok: bool = True
    github_user: str
    github_user_id: int | None
    created_by_user: str
    reporting_status: Literal["pending_metadata", "complete"]
    label: str | None = None
    inserted_at: datetime
    updated_at: datetime | None = None
    deleted_at: datetime | None = None

    @computed_field
    @property
    def deleted(self) -> bool:
        """True when the session has been soft-deleted (deleted_at is set)."""
        return self.deleted_at is not None


class SessionUpdate(BaseModel):
    """Partial update for an existing session.

    Only mutable fields are exposed. `duration_ms` is the main use case:
    a user forgot to stop a timer and needs to correct it. When duration
    changes, the server recomputes `started_at` and `duration_hours` so
    the row remains internally consistent.
    """

    model_config = ConfigDict(extra="forbid")

    duration_ms: int | None = Field(default=None, ge=0)
    issue_title: str | None = None
    client_id: int | None = None
    reporting_project_id: str | None = None
    project: str | None = None
    description: str | None = None


# --- Clients ---


class ClientProject(BaseModel):
    project_id: str
    title: str
    repositories: list[str] = Field(default_factory=list)


class Client(BaseModel):
    client_id: int
    name: str
    active: bool = True
    projects: list[ClientProject] = Field(default_factory=list)
    repositories: list[str] = Field(default_factory=list)


class ClientCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1, max_length=255)


class ClientProjectUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    project_id: str = Field(min_length=1, max_length=255)
    title: str = Field(min_length=1)
    org: str | None = None


class ProjectRepositoryUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    repo: str = Field(min_length=3, max_length=512)


# --- Projects (lookup table) ---


class Project(BaseModel):
    """A GitHub Projects v2 entry in the projects lookup table.

    Sessions reference projects by `project_id` (stable node id). The
    `title` here is the current name — update this row on a rename and
    every session that references the id reflects the new name.
    """

    model_config = ConfigDict(extra="ignore")

    project_id: str = Field(description="Stable GitHub Projects v2 node id.")
    title: str
    org: str | None = None


# --- Members ---


class Member(BaseModel):
    github_login: str
    github_user_id: int | None = None
    role: Literal["admin", "member"] = "member"
    status: Literal["active", "revoked", "pending"] = "active"
    source: Literal["org", "manual"] = "manual"
    added_by: str | None = None
    added_at: datetime | None = None
    updated_at: datetime | None = None


class MemberUpdate(BaseModel):
    """Admin-only payload to add/update a member."""

    model_config = ConfigDict(extra="forbid")

    github_login: str
    role: Literal["admin", "member"] | None = None
    status: Literal["active", "revoked", "pending"] | None = None


# --- Org config ---


class OrgConfig(BaseModel):
    org_login: str
    default_field_name: str | None = None
    # Keyed by the stable Projects v2 node id (rename-proof). The extension
    # still accepts legacy title keys for read until the config is re-saved.
    project_fields: dict[str, str] = Field(default_factory=dict)
    # Stable Projects v2 node ids (rename-proof); legacy title values are
    # tolerated for read.
    excluded_projects: list[str] = Field(default_factory=list)
    updated_by: str | None = None
    updated_at: datetime | None = None


class OrgConfigUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default_field_name: str | None = None
    project_fields: dict[str, str] | None = None
    excluded_projects: list[str] | None = None
