"""Pydantic models — wire format for the API and shape for BigQuery rows."""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

# --- Identity ---


class GitHubUser(BaseModel):
    """Resolved identity from a PAT — what GitHub returned for /user."""

    login: str
    id: int


class Me(BaseModel):
    """Response from /v1/me — extension uses this to gate UI."""

    login: str
    id: int
    role: Literal["admin", "member"]
    status: Literal["active", "revoked", "pending"]
    org_member: bool


# --- Sessions ---


class SessionIn(BaseModel):
    """A time-tracking session pushed by the extension on STOP."""

    model_config = ConfigDict(extra="forbid")

    session_id: str = Field(description="UUID generated by the extension at STOP time.")
    project: str | None = Field(
        default=None,
        description="Auto-derived label: the issue's GitHub Project title, else the "
        "repo (owner/name). The server falls back to repo if a client omits it.",
    )
    repo: str | None = Field(default=None, description="owner/name.")
    issue_number: int
    issue_title: str | None = None
    issue_url: str | None = None
    started_at: datetime
    completed_at: datetime
    duration_ms: int = Field(ge=0)
    duration_hours: float = Field(ge=0)
    source_url: str | None = None
    synced_to_project: bool = False
    project_titles: list[str] = Field(default_factory=list)
    takt_version: str | None = None
    client_ts: datetime | None = None


class SessionOut(SessionIn):
    """A session row returned from BigQuery."""

    github_user: str
    github_user_id: int
    inserted_at: datetime
    deleted_at: datetime | None = None


class SessionUpdate(BaseModel):
    """Partial update for an existing session.

    Only mutable fields are exposed. `duration_ms` is the main use case:
    a user forgot to stop a timer and needs to correct it. When duration
    changes, the server recomputes `started_at` and `duration_hours` so
    the row remains internally consistent.
    """

    model_config = ConfigDict(extra="forbid")

    duration_ms: int | None = Field(default=None, ge=0)
    issue_title: str | None = None


# --- Members ---


class Member(BaseModel):
    github_login: str
    github_user_id: int | None = None
    role: Literal["admin", "member"] = "member"
    status: Literal["active", "revoked", "pending"] = "active"
    source: Literal["org", "manual"] = "manual"
    added_by: str | None = None
    added_at: datetime | None = None
    updated_at: datetime | None = None


class MemberUpdate(BaseModel):
    """Admin-only payload to add/update a member."""

    model_config = ConfigDict(extra="forbid")

    github_login: str
    role: Literal["admin", "member"] | None = None
    status: Literal["active", "revoked", "pending"] | None = None


# --- Org config ---


class OrgConfig(BaseModel):
    org_login: str
    default_field_name: str | None = None
    project_fields: dict[str, str] = Field(default_factory=dict)
    excluded_projects: list[str] = Field(default_factory=list)
    updated_by: str | None = None
    updated_at: datetime | None = None


class OrgConfigUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default_field_name: str | None = None
    project_fields: dict[str, str] | None = None
    excluded_projects: list[str] | None = None
