-- Takt BigQuery schema.
--
-- Table names use the placeholder `__TAKT_DS__` for `<project>.<dataset>` so
-- the same schema can target production (cost-tracker-490815.takt) or a test
-- dataset (cost-tracker-490815.takt_test). Substitute before applying:
--
--   sed 's/__TAKT_DS__/cost-tracker-490815.takt/g' schema.sql \
--     | bq query --project_id=cost-tracker-490815 --location=EU --use_legacy_sql=false
--
-- Easiest is to let scripts/bootstrap.sh do it (it honours BQ_DATASET):
--
--   BQ_DATASET=takt      ADMIN_LOGIN=<login> ./server/scripts/bootstrap.sh  # prod
--   BQ_DATASET=takt_test ADMIN_LOGIN=<login> ./server/scripts/bootstrap.sh  # test
--
-- Idempotent: safe to re-run.

-- Dataset is created out-of-band by scripts/bootstrap.sh because `bq query`
-- cannot create datasets. See server/scripts/bootstrap.sh.

-- ============================================================================
-- sessions: the canonical time log
-- ============================================================================
CREATE TABLE IF NOT EXISTS `__TAKT_DS__.sessions` (
  session_id        STRING NOT NULL OPTIONS(description="UUID generated by the extension at STOP time."),
  github_user       STRING NOT NULL OPTIONS(description="GitHub login at the time of write."),
  github_user_id    INT64  NOT NULL OPTIONS(description="Stable GitHub user id (survives renames)."),
  repo              STRING NOT NULL OPTIONS(description="owner/name."),
  issue_number      INT64  NOT NULL,
  issue_title       STRING,
  issue_url         STRING,
  started_at        TIMESTAMP NOT NULL,
  completed_at      TIMESTAMP NOT NULL,
  duration_ms       INT64 NOT NULL,
  duration_hours    FLOAT64 NOT NULL,
  source_url        STRING OPTIONS(description="Page URL where the timer ran (issue or project pane)."),
  synced_to_project BOOL,
  project_titles    ARRAY<STRING> OPTIONS(description="Deprecated: legacy snapshot of titles at STOP time. Current titles live in the projects table; reads join on project_ids."),
  project_ids       ARRAY<STRING> OPTIONS(description="Stable Projects v2 node ids. FK-like reference into the projects table. Rename-proof grouping key."),
  takt_version      STRING,
  client_ts         TIMESTAMP OPTIONS(description="Client timestamp at push time."),
  inserted_at       TIMESTAMP NOT NULL OPTIONS(description="Server insert timestamp."),
  deleted_at        TIMESTAMP OPTIONS(description="Soft-delete marker; NULL = active.")
)
PARTITION BY DATE(completed_at)
CLUSTER BY github_user, repo
OPTIONS(
  description = "Takt time-tracking sessions. One row per stopped timer."
);

-- Backfill the column onto tables created before project_ids existed.
-- ADD COLUMN IF NOT EXISTS is idempotent, so this is safe to re-run.
ALTER TABLE `__TAKT_DS__.sessions`
  ADD COLUMN IF NOT EXISTS project_ids ARRAY<STRING>;

-- ============================================================================
-- projects: lookup table for GitHub Projects v2 (rename-proof)
-- ============================================================================
-- Sessions reference projects by stable node id (project_ids). This table
-- holds the current title for each id, so a project rename is a single
-- UPDATE here — every session that references the id instantly reflects
-- the new name. The extension upserts rows on STOP; a sync script can
-- batch-refresh from the GitHub API.
CREATE TABLE IF NOT EXISTS `__TAKT_DS__.projects` (
  project_id   STRING NOT NULL OPTIONS(description="Stable GitHub Projects v2 node id. Primary key."),
  title        STRING NOT NULL OPTIONS(description="Current project title (mutable; updated on rename)."),
  org          STRING OPTIONS(description="GitHub org login that owns the project."),
  updated_at   TIMESTAMP NOT NULL OPTIONS(description="Last upsert timestamp.")
)
OPTIONS(
  description = "GitHub Projects v2 lookup table. Sessions reference by project_id; title is mutable."
);

-- ============================================================================
-- members: who is allowed to use Takt
-- ============================================================================
CREATE TABLE IF NOT EXISTS `__TAKT_DS__.members` (
  github_login    STRING NOT NULL,
  github_user_id  INT64,
  role            STRING NOT NULL OPTIONS(description="'admin' | 'member'."),
  status          STRING NOT NULL OPTIONS(description="'active' | 'revoked' | 'pending'."),
  source          STRING NOT NULL OPTIONS(description="'org' (auto via GitHub org) | 'manual'."),
  added_by        STRING,
  added_at        TIMESTAMP,
  updated_at      TIMESTAMP
)
OPTIONS(
  description = "Takt access list. Org members are auto-added on first use; admins can override."
);

-- ============================================================================
-- org_config: singleton-style config table (one row per org)
-- ============================================================================
CREATE TABLE IF NOT EXISTS `__TAKT_DS__.org_config` (
  org_login          STRING NOT NULL,
  default_field_name STRING OPTIONS(description="Default Projects v2 NUMBER field for time sync."),
  project_fields     STRING OPTIONS(description="JSON: {projectId: fieldName} per-project overrides (stable id key, rename-proof)."),
  excluded_projects  ARRAY<STRING> OPTIONS(description="Stable Projects v2 node ids to exclude from sync (rename-proof)."),
  updated_by         STRING,
  updated_at         TIMESTAMP
)
OPTIONS(
  description = "Org-level Takt configuration. Replaces per-user field mapping."
);

-- ============================================================================
-- audit_log: admin actions and config changes (write-only)
-- ============================================================================
CREATE TABLE IF NOT EXISTS `__TAKT_DS__.audit_log` (
  ts        TIMESTAMP NOT NULL,
  actor     STRING NOT NULL,
  action    STRING NOT NULL OPTIONS(description="e.g. 'member.upsert', 'config.update', 'session.delete'."),
  target    STRING,
  payload   STRING OPTIONS(description="JSON snapshot of the change.")
)
PARTITION BY DATE(ts)
OPTIONS(
  description = "Append-only audit trail of admin actions."
);

-- ============================================================================
-- session_facts: hourly PostgreSQL analytics replica
-- ============================================================================
CREATE TABLE IF NOT EXISTS `__TAKT_DS__.session_facts` (
  session_id        STRING NOT NULL,
  github_user       STRING NOT NULL,
  github_user_id    INT64,
  created_by_user   STRING NOT NULL,
  source            STRING NOT NULL,
  entry_type        STRING NOT NULL,
  reporting_status  STRING NOT NULL,
  client_id         INT64,
  client            STRING,
  reporting_project_id STRING,
  project           STRING,
  description       STRING,
  label             STRING,
  github_metadata   JSON,
  context_type      STRING,
  repo              STRING,
  issue_number      INT64 NOT NULL,
  issue_title       STRING,
  issue_url         STRING,
  category          STRING,
  category_title    STRING,
  started_at        TIMESTAMP NOT NULL,
  completed_at      TIMESTAMP NOT NULL,
  duration_ms       INT64 NOT NULL,
  duration_hours_exact FLOAT64 NOT NULL,
  duration_hours    FLOAT64 NOT NULL,
  source_url        STRING,
  synced_to_project BOOL,
  project_titles    ARRAY<STRING>,
  project_ids       ARRAY<STRING>,
  takt_version      STRING,
  client_ts         TIMESTAMP,
  inserted_at       TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP NOT NULL,
  deleted_at        TIMESTAMP,
  replicated_at     TIMESTAMP NOT NULL
)
PARTITION BY DATE(completed_at)
CLUSTER BY github_user, entry_type, client, repo
OPTIONS(
  description = "Hourly analytics replica sourced transactionally from PostgreSQL."
);

CREATE OR REPLACE VIEW `__TAKT_DS__.time_tracking` AS
SELECT
  CASE
    WHEN source = 'github' THEN 'github_timer'
    WHEN entry_type = 'delivery' THEN 'manual_delivery'
    ELSE 'manual_ops'
  END AS route,
  source,
  entry_type AS type,
  github_user AS user,
  client,
  IF(entry_type = 'ops', NULL, repo) AS repo,
  project,
  IF(issue_number > 0, issue_number, NULL) AS issue,
  description,
  duration_hours_exact AS hours,
  duration_hours AS hours_rounded,
  label,
  github_metadata
FROM `__TAKT_DS__.session_facts`
WHERE deleted_at IS NULL
  AND reporting_status = 'complete';
