-- Takt BigQuery schema.
-- Run with: bq query --project_id=cost-tracker-490815 --use_legacy_sql=false < schema.sql
-- Adjust the dataset location below if billing_export is not in the EU.

-- Idempotent: safe to re-run.

-- Dataset is created out-of-band by scripts/bootstrap.sh because `bq query`
-- cannot create datasets. See server/scripts/bootstrap.sh.

-- ============================================================================
-- sessions: the canonical time log
-- ============================================================================
CREATE TABLE IF NOT EXISTS `cost-tracker-490815.takt.sessions` (
  session_id        STRING NOT NULL OPTIONS(description="UUID generated by the extension at STOP time."),
  github_user       STRING NOT NULL OPTIONS(description="GitHub login at the time of write."),
  github_user_id    INT64  NOT NULL OPTIONS(description="Stable GitHub user id (survives renames)."),
  project           STRING OPTIONS(description="User-selected project label (from org_config.projects). NULL for issue-page timers / legacy rows."),
  repo              STRING OPTIONS(description="owner/name. Optional link; NULL when no repo is attached."),
  issue_number      INT64  NOT NULL,
  issue_title       STRING,
  issue_url         STRING,
  started_at        TIMESTAMP NOT NULL,
  completed_at      TIMESTAMP NOT NULL,
  duration_ms       INT64 NOT NULL,
  duration_hours    FLOAT64 NOT NULL,
  source_url        STRING OPTIONS(description="Page URL where the timer ran (issue or project pane)."),
  synced_to_project BOOL,
  project_titles    ARRAY<STRING>,
  takt_version      STRING,
  client_ts         TIMESTAMP OPTIONS(description="Client timestamp at push time."),
  inserted_at       TIMESTAMP NOT NULL OPTIONS(description="Server insert timestamp."),
  deleted_at        TIMESTAMP OPTIONS(description="Soft-delete marker; NULL = active.")
)
PARTITION BY DATE(completed_at)
CLUSTER BY github_user, repo
OPTIONS(
  description = "Takt time-tracking sessions. One row per stopped timer."
);

-- Add `project` to pre-existing sessions tables. Existing rows get NULL.
ALTER TABLE `cost-tracker-490815.takt.sessions`
  ADD COLUMN IF NOT EXISTS project STRING
  OPTIONS(description="User-selected project label (from org_config.projects). NULL for issue-page timers / legacy rows.");
-- Note: `repo` was created NOT NULL on older tables. BigQuery cannot drop a
-- NOT NULL constraint via DDL, so writes from the extension always send a repo
-- string (possibly empty) and reads tolerate it. New tables create repo nullable.

-- ============================================================================
-- members: who is allowed to use Takt
-- ============================================================================
CREATE TABLE IF NOT EXISTS `cost-tracker-490815.takt.members` (
  github_login    STRING NOT NULL,
  github_user_id  INT64,
  role            STRING NOT NULL OPTIONS(description="'admin' | 'member'."),
  status          STRING NOT NULL OPTIONS(description="'active' | 'revoked' | 'pending'."),
  source          STRING NOT NULL OPTIONS(description="'org' (auto via GitHub org) | 'manual'."),
  added_by        STRING,
  added_at        TIMESTAMP,
  updated_at      TIMESTAMP
)
OPTIONS(
  description = "Takt access list. Org members are auto-added on first use; admins can override."
);

-- ============================================================================
-- org_config: singleton-style config table (one row per org)
-- ============================================================================
CREATE TABLE IF NOT EXISTS `cost-tracker-490815.takt.org_config` (
  org_login          STRING NOT NULL,
  default_field_name STRING OPTIONS(description="Default Projects v2 NUMBER field for time sync."),
  project_fields     STRING OPTIONS(description="JSON: {projectTitle: fieldName} per-project overrides."),
  excluded_projects  ARRAY<STRING>,
  projects           ARRAY<STRING> OPTIONS(description="Managed list of project labels offered in the My Time Add-entry picker."),
  project_repos      STRING OPTIONS(description="JSON: {projectLabel: [repo, ...]} linked repos per project (many-to-many)."),
  updated_by         STRING,
  updated_at         TIMESTAMP
)
OPTIONS(
  description = "Org-level Takt configuration. Replaces per-user field mapping."
);

-- Add `projects` (managed label list) to pre-existing org_config tables.
ALTER TABLE `cost-tracker-490815.takt.org_config`
  ADD COLUMN IF NOT EXISTS projects ARRAY<STRING>
  OPTIONS(description="Managed list of project labels offered in the My Time Add-entry picker.");
-- Add `project_repos` (JSON: project label -> linked repos) to pre-existing tables.
ALTER TABLE `cost-tracker-490815.takt.org_config`
  ADD COLUMN IF NOT EXISTS project_repos STRING
  OPTIONS(description="JSON: {projectLabel: [repo, ...]} linked repos per project (many-to-many).");

-- ============================================================================
-- audit_log: admin actions and config changes (write-only)
-- ============================================================================
CREATE TABLE IF NOT EXISTS `cost-tracker-490815.takt.audit_log` (
  ts        TIMESTAMP NOT NULL,
  actor     STRING NOT NULL,
  action    STRING NOT NULL OPTIONS(description="e.g. 'member.upsert', 'config.update', 'session.delete'."),
  target    STRING,
  payload   STRING OPTIONS(description="JSON snapshot of the change.")
)
PARTITION BY DATE(ts)
OPTIONS(
  description = "Append-only audit trail of admin actions."
);
